<?php
$data = array (
  4 => 
  array (
    'cat_id' => '4',
    'cat_name' => '化妆品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '4',
    'name' => '化妆品',
  ),
  5 => 
  array (
    'cat_id' => '5',
    'cat_name' => '手机专区',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '11',
    'level' => 0,
    'id' => '5',
    'name' => '手机专区',
  ),
  6 => 
  array (
    'cat_id' => '6',
    'cat_name' => '零食专区',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '6',
    'name' => '零食专区',
  ),
  3 => 
  array (
    'cat_id' => '3',
    'cat_name' => '服装',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '3',
    'name' => '服装',
  ),
);
?>